In [2]:
import pandas as pd

daily_return_df = pd.read_csv('sp500_joined_daily_returns_yahoo.csv')
daily_return_df.set_index('Date', inplace=True)
daily_return_df

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,-0.420879,-0.395606,NaN,-0.014346,NaN,-0.064721,-0.031990,0.035491,NaN,-0.255485,...,-0.608536,-0.304356,-0.310023,NaN,-0.283451,-0.034815,NaN,-0.322457,NaN,-0.335147
2000-01-04,-0.424806,-0.399022,NaN,-0.037162,NaN,-0.114259,-0.053371,-0.033058,NaN,-0.256409,...,-0.587705,-0.358993,-0.290556,NaN,-0.268203,-0.014428,NaN,-0.303260,NaN,-0.340144
2000-01-05,-0.396778,-0.384488,NaN,0.054945,NaN,-0.093212,0.044063,0.032258,NaN,-0.224806,...,-0.580057,-0.291187,-0.297410,NaN,-0.259446,0.066588,NaN,-0.279348,NaN,-0.321987
2000-01-06,-0.370289,-0.371148,NaN,0.023050,NaN,-0.114423,-0.002024,0.032258,NaN,-0.228983,...,-0.598170,-0.322374,-0.341881,NaN,-0.260714,-0.041970,NaN,-0.269102,NaN,-0.331391
2000-01-07,-0.401052,-0.373645,NaN,-0.003472,NaN,-0.089726,0.044336,0.054767,NaN,-0.214733,...,-0.595659,-0.311802,-0.214726,NaN,-0.275959,-0.006455,NaN,-0.281024,NaN,-0.296027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-30,-0.017295,0.004176,-0.005137,0.001388,0.000120,0.014811,-0.003187,0.061033,-0.010915,-0.025274,...,-0.003698,-0.047018,0.058622,-0.008779,-0.003766,-0.000159,-0.007455,-0.019563,-0.012925,-0.002122
2020-12-01,-0.021237,-0.006866,-0.009614,-0.014332,0.003022,-0.000125,-0.005934,0.004119,0.023747,-0.002904,...,0.011683,-0.006278,0.005517,-0.004614,-0.004680,-0.024788,-0.029171,0.013661,-0.001732,0.001231
2020-12-02,0.009339,-0.001477,0.009519,-0.011073,-0.004188,-0.007150,0.011752,0.009151,-0.018058,0.033203,...,0.007334,0.014324,0.008985,-0.000935,-0.008407,-0.009441,0.017130,0.040000,-0.012733,0.005400
2020-12-03,0.004619,-0.005733,-0.002476,0.011562,-0.000280,-0.006557,0.004293,-0.018605,0.010091,0.002369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000027
2020-12-04,0.001917,0.007658,0.021520,0.025737,0.012869,0.027439,0.000679,0.015770,0.016738,-0.008004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004438

### Follow The Leader ###

In [15]:
# Follow the leader:
windows = [5,10,20,40,60]
W = pd.DataFrame().reindex(columns = daily_return_df.columns, index = windows)
for col in W.columns:
    W[col].values[:] = 0
print(W)
prev_beta_error_df = None
concat = None
for w in windows:
    beta_df = daily_return_df.rolling(window=w).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=w).var(), axis=0)
    act_beta_error_df = (daily_return_df - beta_df.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2
    print(act_beta_error_df)
#     act_beta_error_df.columns = act_beta_error_df.columns + "_{0}".format(w)
#     if concat is not None:
#         concat = pd.concat([concat,act_beta_error_df], axis=1)
#     else:
#         concat = act_beta_error_df

    MMM  ABT  ABBV  ABMD  ACN  ATVI  ADBE  AMD  AAP  AES  ...  XEL  XRX  XLNX  \
5   0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
10  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
20  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
40  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
60  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0

    XYL  YUM  ZBRA  ZBH  ZION  ZTS  SPY
5   0.0  0.0   0.0  0.0   0.0  0.0  0.0
10  0.0  0.0   0.0  0.0   0.0  0.0  0.0
20  0.0  0.0   0.0  0.0   0.0  0.0  0.0
40  0.0  0.0   0.0  0.0   0.0  0.0  0.0
60  0.0  0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 506 columns]
                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07  0.119369  0.084679       NaN  0.007813       NaN  0.002548
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.119270  0.084399  0.043434  0.015602  0.040028  0.102625
2020-12-01  0.118404  0.105793  0.041023  0.025596  0.043709  0.129410
2020-12-02  0.168648  0.011608  0.062181  0.192750  0.005462  0.233283
2020-12-03  0.246400  0.027889  0.103079  0.353682  0.010543  0.198686
2020-12-04  0.263291  0.004340  0.339749  0.005402  0.008600  0.000854

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
2000-01-03       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-07  0.177506  0.085090       NaN  0.002621  ...  0.342175  0.039387
...              ...       ...       ...       ...  ...       ...       ...
2020-11-30  0.001325  0.341587  0.192785  0.382687  ...  0.001189  0.370818
2020-12-01  0.000354  0.444161  0.253844  0.408633  ...  0.001027  0.468910
2020-12-02  0.060145  0.400392  0.024495  1.594518  ...  0.115192  0.922477
2020-12-03  0.104845  0.397246  0.061698  1.605439  ...       NaN       NaN
2020-12-04  0.059337  0.365475  0.000704  0.802524  ...       NaN       NaN

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07  0.033380       NaN  0.083726  0.014248       NaN  0.032282
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.356648  0.148855  0.097537  0.086474  0.272147  0.710348
2020-12-01  0.458390  0.147200  0.087457  0.061732  0.239870  0.818407
2020-12-02  0.437360  0.025961  0.026311  0.062687  0.246829  2.073486
2020-12-03       NaN       NaN       NaN       NaN       NaN       NaN
2020-12-04       NaN       NaN       NaN       NaN       NaN       NaN

                 ZTS       SPY
Date
2000-01-03       NaN       NaN
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN  0.013536
...              ...       ...
2020-11-30  0.042238  0.031528
2020-12-01  0.037029  0.032730
2020-12-02  0.002305  0.034256
2020-12-03       NaN  0.032296
2020-12-04       NaN  0.033901

[5266 rows x 506 columns]
                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.047407  0.046504  0.009037  0.014167  0.037707  0.018136
2020-12-01  0.043042  0.027034  0.017267  0.012161  0.040766  0.011460
2020-12-02  0.067516  0.026997  0.027932  0.004820  0.026589  0.005164
2020-12-03  0.027291  0.007822  0.012534  0.003097  0.013732  0.021605
2020-12-04  0.022052  0.012697  0.033457  0.004599  0.023849  0.028517

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
2000-01-03       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN  ...       NaN       NaN
...              ...       ...       ...       ...  ...       ...       ...
2020-11-30  0.035356  0.046093  0.003519  0.008859  ...  0.020296  0.069566
2020-12-01  0.036024  0.010845  0.037009  0.011733  ...  0.020486  0.068076
2020-12-02  0.044764  0.014398  0.007656  0.052443  ...  0.037038  0.096043
2020-12-03  0.032448  0.000489  0.018920  0.197143  ...       NaN       NaN
2020-12-04  0.013367  0.008134  0.081157  0.303113  ...       NaN       NaN

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.041930  0.020359  0.026619  0.198291  0.015480  0.095579
2020-12-01  0.011773  0.015319  0.023273  0.195531  0.023239  0.173267
2020-12-02  0.014277  0.017248  0.012814  0.157616  0.052565  0.247344
2020-12-03       NaN       NaN       NaN       NaN       NaN       NaN
2020-12-04       NaN       NaN       NaN       NaN       NaN       NaN

                 ZTS       SPY
Date
2000-01-03       NaN       NaN
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
...              ...       ...
2020-11-30  0.000650  0.031528
2020-12-01  0.002036  0.032730
2020-12-02  0.000005  0.034256
2020-12-03       NaN  0.032296
2020-12-04       NaN  0.033901

[5266 rows x 506 columns]
                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.082302  0.028672  0.004613  0.004968  0.011745  0.001020
2020-12-01  0.078126  0.024532  0.003623  0.002678  0.012344  0.000284
2020-12-02  0.106297  0.024053  0.010570  0.001633  0.007195  0.000078
2020-12-03  0.132290  0.019827  0.006111  0.004420  0.006182  0.000011
2020-12-04  0.130411  0.025299  0.016211  0.009803  0.009852  0.003909

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
2000-01-03       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN  ...       NaN       NaN
...              ...       ...       ...       ...  ...       ...       ...
2020-11-30  0.077857  0.026079  0.024918  0.038017  ...  0.016428  0.001293
2020-12-01  0.075901  0.010989  0.038959  0.047041  ...  0.021515  0.000005
2020-12-02  0.087131  0.009401  0.013224  0.082719  ...  0.018960  0.000292
2020-12-03  0.076269  0.003684  0.029041  0.083644  ...       NaN       NaN
2020-12-04  0.074932  0.011508  0.037510  0.062499  ...       NaN       NaN

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.028935  0.052343  0.028018  0.068441  0.020795  0.160796
2020-12-01  0.013830  0.053998  0.027378  0.053105  0.013730  0.133202
2020-12-02  0.013759  0.046484  0.024928  0.051840  0.027568  0.107708
2020-12-03       NaN       NaN       NaN       NaN       NaN       NaN
2020-12-04       NaN       NaN       NaN       NaN       NaN       NaN

                 ZTS       SPY
Date
2000-01-03       NaN       NaN
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
...              ...       ...
2020-11-30  0.059221  0.031528
2020-12-01  0.064758  0.032730
2020-12-02  0.060260  0.034256
2020-12-03       NaN  0.032296
2020-12-04       NaN  0.033901

[5266 rows x 506 columns]

                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.028773  0.018836  0.010459  0.008091  0.013512  0.007519
2020-12-01  0.029213  0.015180  0.009624  0.003034  0.017592  0.004563
2020-12-02  0.045818  0.012993  0.008875  0.002063  0.012436  0.002153
2020-12-03  0.044536  0.012522  0.007367  0.004745  0.013846  0.002368
2020-12-04  0.044280  0.016286  0.014630  0.008567  0.018597  0.009233

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
2000-01-03       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN  ...       NaN       NaN
...              ...       ...       ...       ...  ...       ...       ...
2020-11-30  0.048583  0.060409  0.018404  0.016601  ...  0.007686  0.010909
2020-12-01  0.048643  0.026437  0.032025  0.027376  ...  0.009128  0.019100
2020-12-02  0.062586  0.026891  0.012260  0.051785  ...  0.015091  0.031147
2020-12-03  0.055944  0.018080  0.018776  0.042506  ...       NaN       NaN
2020-12-04  0.055908  0.032001  0.022458  0.034569  ...       NaN       NaN

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.053204  0.021941  0.020728  0.043929  0.034385  0.000265
2020-12-01  0.031794  0.022131  0.027084  0.029677  0.023447  0.001280
2020-12-02  0.035410  0.023923  0.019713  0.041326  0.048499  0.002565
2020-12-03       NaN       NaN       NaN       NaN       NaN       NaN
2020-12-04       NaN       NaN       NaN       NaN       NaN       NaN

                 ZTS       SPY
Date
2000-01-03       NaN       NaN
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
...              ...       ...
2020-11-30  0.033385  0.031528
2020-12-01  0.042125  0.032730
2020-12-02  0.035375  0.034256
2020-12-03       NaN  0.032296
2020-12-04       NaN  0.033901

[5266 rows x 506 columns]
                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.018591  0.018837  0.010480  0.029490  0.016788  0.010587
2020-12-01  0.016849  0.015374  0.009398  0.017500  0.016459  0.008262
2020-12-02  0.026247  0.017117  0.012781  0.018095  0.015697  0.006925
2020-12-03  0.024610  0.015592  0.010269  0.024233  0.016567  0.006482
2020-12-04  0.025336  0.020367  0.014987  0.029383  0.016650  0.014407

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
2000-01-03       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN  ...       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN  ...       NaN       NaN
...              ...       ...       ...       ...  ...       ...       ...
2020-11-30  0.057013  0.075230  0.019707  0.010199  ...  0.012523  0.016405
2020-12-01  0.054621  0.051496  0.031008  0.014767  ...  0.015526  0.029912
2020-12-02  0.064050  0.059218  0.017212  0.027393  ...  0.014086  0.042155
2020-12-03  0.059796  0.045984  0.025194  0.018467  ...       NaN       NaN
2020-12-04  0.061718  0.055281  0.033582  0.016622  ...       NaN       NaN

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
2000-01-03       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...       ...
2020-11-30  0.049073  0.016694  0.016404  0.037258  0.021688  0.005217
2020-12-01  0.029359  0.017489  0.015219  0.024915  0.015118  0.012074
2020-12-02  0.030383  0.019071  0.013260  0.027333  0.031519  0.018047
2020-12-03       NaN       NaN       NaN       NaN       NaN       NaN
2020-12-04       NaN       NaN       NaN       NaN       NaN       NaN

                 ZTS       SPY
Date
2000-01-03       NaN       NaN
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
...              ...       ...
2020-11-30  0.019744  0.031528
2020-12-01  0.023056  0.032730
2020-12-02  0.018255  0.034256
2020-12-03       NaN  0.032296
2020-12-04       NaN  0.033901

[5266 rows x 506 columns]

In [346]:
import numpy as np

windows = [5,10,20,40,60]
min_windows = pd.DataFrame().reindex_like(daily_return_df)
concat = None
for w in windows:
    beta_df = daily_return_df.rolling(window=w).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=w).var(), axis=0)
    act_beta_error_df = (daily_return_df - beta_df.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2    
    act_beta_error_df.columns = act_beta_error_df.columns + "_{0}".format(w)
    if concat is not None:
        concat = pd.concat([concat,act_beta_error_df], axis=1)
    else:
        concat = act_beta_error_df
concat

,MMM_5,ABT_5,ABBV_5,ABMD_5,ACN_5,ATVI_5,ADBE_5,AMD_5,AAP_5,AES_5,...,XEL_60,XRX_60,XLNX_60,XYL_60,YUM_60,ZBRA_60,ZBH_60,ZION_60,ZTS_60,SPY_60
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2020,0.000213,2.110161e-07,1.546639e-05,4.015859e-07,2.770852e-06,0.000005,1.407871e-04,7.069349e-07,0.000121,0.000017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/20/2020,0.000063,9.875417e-07,7.836516e-05,7.779479e-05,5.149185e-06,0.000208,2.554870e-05,6.194058e-05,0.000115,0.000223,...,6.727225e-10,0.000045,0.000008,0.000004,0.000003,5.482825e-04,0.000001,0.000050,0.000017,3.894700e-05
11/23/2020,0.000004,3.873034e-04,4.914337e-06,4.137345e-05,3.476339e-05,0.000175,7.935690e-05,7.527488e-06,0.000322,0.000052,...,3.633239e-04,0.000336,0.000002,0.000048,0.000033,1.496023e-04,0.000006,0.000243,0.000123,1.108893e-07
11/24/2020,0.000137,2.471371e-04,1.070634e-04,9.129314e-06,1.056217e-04,0.000087,6.840774e-06,6.006421e-05,0.000332,0.000428,...,4.851106e-05,0.000293,0.000048,0.000202,0.000200,1.528029e-04,0.000533,0.001228,0.000417,6.700206e-05
11/25/2020,0.000002,3.516814e-05,1.308463e-05,5.185756e-05,8.028811e-06,0.000060,6.389913e-05,1.184563e-04,0.000051,0.000069,...,1.309120e-06,0.000017,0.000131,0.000060,0.000009,6.561605e-05,0.000024,0.000003,0.000127,2.146493e-06
11/27/2020,0.000028,8.323127e-05,8.053154e-07,8.936498e-04,1.510583e-11,0.000035,4.526880e-08,8.192247e-05,0.000006,0.000005,...,1.071439e-04,0.000020,0.000003,0.000006,0.000002,7.450207e-08,0.000010,0.000591,0.000001,4.070140e-07

In [378]:
min_windows = pd.DataFrame()
for ticker in daily_return_df.columns:
    prefix = ticker + '_'
    head = [prefix + "5", prefix + "10", prefix + "20", prefix + "40", prefix + "60"]
    min_windows[ticker] = concat[head].idxmin(axis=1).str.replace(prefix,"")
min_windows

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2020,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/20/2020,10,5,40,20,10,5,40,10,5,5,...,10,5,10,5,20,40,5,5,5,5
11/23/2020,20,20,5,20,10,20,40,10,40,5,...,5,10,10,5,5,40,10,5,10,40
11/24/2020,20,20,5,20,10,20,20,10,40,20,...,40,10,10,10,10,5,40,5,10,5
11/25/2020,20,5,10,20,20,10,20,60,10,60,...,5,10,60,60,20,40,10,10,5,5
11/27/2020,5,10,5,60,5,10,20,5,10,10,...,5,20,60,60,5,40,20,20,5,5

In [379]:

d = pd.DataFrame(np.zeros((df.shape)), index=df.index, columns=df.columns)

cumsum_df = daily_return_df.cumsum(axis=0) #vegtelen ablak
print(cumsum_df)
# cumsum_df = daily_return_df.rolling(window=100) #rolling min (nem az egeszen, csak pl 100 napon)
# # melyikre teljes\t jobban? fel-1-20... evek vagy a vegtelen
# # follow the leader x ev
# # ftl vegtelen, stb.

# #cumsum.idxmin(axis=1)
# #print(d)
# for ind,row in cumsum_df.idxmin(axis=1).items():
#     #print(ind)
#     #print(row)
#     d.loc[ind,row] = 1

# shifted = d.shift(1) # Mert a tegnapig kapott adatokat nezzuk
# shifted = shifted.mul(df)
# print(df.tail())
# print(df.shift(1).tail())
# shifted.sum(axis=1).cumsum().plot()
# cumsum_df["follow the leader"] = shifted.sum(axis=1).cumsum()
# cumsum_df

# # A mai legjobbat a holnapi legjobbal kell szamolni: shift 1

# # Feature set a kapott beta ablakokkal minden evre, minden modell csak a sajat evet nezi
# # melyik nap 
# # volatilis iszoszakok: beta ablak
# # X: amit felhasznalok feature, Y: a kimenet
# # X-et kitalalom pl. az elmult valamennyi nap alapjan a tulajdonsagok
# # minden napra visszamegyek egy param pl 5 napot, es 
# # daily return, szoras
# # beta window melle a volume


# # kiszamolni minden reszvenyre egy napon belul a legjobb window
# # minden reszveny, datum-ra minden window, es a legkisebbet veszem
# # shift ide nem kell

                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
1/2/2020    0.013057  0.010342  0.005276 -0.021448 -0.003367 -0.021032
1/3/2020    0.021135  0.011974  0.011287 -0.021508  0.002868 -0.010003
1/6/2020    0.029433  0.020383  0.024663  0.053614  0.003636  0.011718
1/7/2020    0.027302  0.021433  0.024213  0.062113  0.007229  0.022607
1/8/2020    0.042077  0.021085  0.028363  0.063851  0.008846  0.020607
...              ...       ...       ...       ...       ...       ...
11/20/2020 -0.229102  0.119007 -0.080462  0.670294  0.258689  0.215344
11/23/2020 -0.226915  0.099622 -0.078108  0.664065  0.264778  0.202343
11/24/2020 -0.215029  0.084070 -0.067610  0.661175  0.275247  0.193124
11/25/2020 -0.213446  0.078092 -0.063950  0.654175  0.272567  0.200763
11/27/2020 -0.218676  0.086998 -0.064808  0.684099  0.272726  0.206426

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
1/2/2020    0.013424  0.047802 -0.006606  0.003005  ... -0.018411 -0.004314
1/3/2020    0.021444  0.059669  0.002190 -0.001520  ... -0.011988 -0.000182
1/6/2020    0.037954  0.067375 -0.003769  0.012657  ... -0.014697 -0.005446
1/7/2020    0.035680  0.045085 -0.016261  0.016653  ... -0.009709 -0.008220
1/8/2020    0.047842  0.044667 -0.027175  0.012681  ... -0.012744 -0.007663
...              ...       ...       ...       ...  ...       ...       ...
11/20/2020  0.212315  0.232695 -0.339508  0.100708  ...  0.247782 -0.436026
11/23/2020  0.203663  0.230240 -0.321535  0.093430  ...  0.228839 -0.417541
11/24/2020  0.206459  0.222657 -0.303184  0.114183  ...  0.221988 -0.400263
11/25/2020  0.214587  0.233734 -0.310097  0.106145  ...  0.220961 -0.395967
11/27/2020  0.214860  0.224642 -0.312160  0.104247  ...  0.210716 -0.400255

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
1/2/2020    0.025214  0.008716  0.012587  0.000425 -0.005201  0.001528
1/3/2020    0.012882  0.025039  0.016826  0.000229  0.004228  0.007169
1/6/2020    0.006750  0.024288  0.020376  0.021566  0.000055  0.006973
1/7/2020    0.019374  0.019157  0.022538  0.017566 -0.004859  0.006382
1/8/2020    0.017563  0.020538  0.039259  0.003080  0.003499  0.013455
...              ...       ...       ...       ...       ...       ...
11/20/2020  0.508396  0.443384  0.050273  0.227411 -0.123044 -0.134808
11/23/2020  0.507347  0.436567  0.044686  0.215398 -0.125296 -0.119147
11/24/2020  0.500636  0.450921  0.058974  0.227978 -0.102065 -0.084033
11/25/2020  0.512278  0.443326  0.056168  0.220099 -0.106786 -0.082321
11/27/2020  0.514173  0.441066  0.057850  0.220046 -0.109843 -0.106554

                 ZTS       SPY
Date
1/2/2020    0.015827  0.004111
1/3/2020    0.028509  0.008003
1/6/2020    0.023650  0.017832
1/7/2020    0.028011  0.016934
1/8/2020    0.024497  0.021610
...              ...       ...
11/20/2020  0.192281  0.032182
11/23/2020  0.181387  0.032686
11/24/2020  0.161131  0.041042
11/25/2020  0.150019  0.039748
11/27/2020  0.149091  0.039281

[230 rows x 506 columns]

AttributeError: 'Rolling' object has no attribute 'idxmin'

In [ ]:
cumsum_df

In [ ]:
# X feature 
# shift-el veszem az elozo x napot, 
pd.DataFrame({"returns" : daily_return_df.stack(), "shifted returns": daily_return_df.shift(1).stack()})
# X feature volume, rolling 
#

In [ ]:
daily_return_df.rolling(10).std()
# szoras, vagy 
daily_return_df.rolling(10).mean()
# Ezekbol csinalom az X-et

# X-bol az Y-t random forest-el szamolom
# A holnapi Y-t a mai X-hez: shift -1 (indexek stimmeljenek)
# Az Y az optimalis window merete

#FTL: minden reszvenyre kell az optimalis window
# --> a kovetkezonek minek kellene lennie

# random forest: default
# szimulacio: megtanitom pl 10-ig(traning), es utana 20-ig(test) ellenorzom
from sicklearn import randomforest
# fit # predict

## step:
# ftl osszehasonlitasa a window-kra, es a vegtelenre
# beta error reszvenyenkent minden ablakra 
## ez lesz az X (+ egy szorast, meg egy arfolyamerteket min, max, volume)
## Y a beta_error reszvenyenkent
# Y minden napra minden reszvenyre kiszamolom az osszes beta window hibajat, es a legkisebb ablakja lesz az Y
# Egy napon belülre számolom az értékeket: 5 érték 

# Fix es X es Y ertekeket megetetetek a random forest-el