In [171]:
import pandas as pd

daily_return_df = pd.read_csv('sp500_joined_daily_returns_yahoo.csv')
daily_return_df.set_index('Date', inplace=True)
daily_return_df

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,-0.420879,-0.395606,NaN,-0.014346,NaN,-0.064721,-0.031990,0.035491,NaN,-0.255485,...,-0.608536,-0.304356,-0.310023,NaN,-0.283451,-0.034815,NaN,-0.322457,NaN,-0.335147
2000-01-04,-0.424806,-0.399022,NaN,-0.037162,NaN,-0.114259,-0.053371,-0.033058,NaN,-0.256409,...,-0.587705,-0.358993,-0.290556,NaN,-0.268203,-0.014428,NaN,-0.303260,NaN,-0.340144
2000-01-05,-0.396778,-0.384488,NaN,0.054945,NaN,-0.093212,0.044063,0.032258,NaN,-0.224806,...,-0.580057,-0.291187,-0.297410,NaN,-0.259446,0.066588,NaN,-0.279348,NaN,-0.321987
2000-01-06,-0.370289,-0.371148,NaN,0.023050,NaN,-0.114423,-0.002024,0.032258,NaN,-0.228983,...,-0.598170,-0.322374,-0.341881,NaN,-0.260714,-0.041970,NaN,-0.269102,NaN,-0.331391
2000-01-07,-0.401052,-0.373645,NaN,-0.003472,NaN,-0.089726,0.044336,0.054767,NaN,-0.214733,...,-0.595659,-0.311802,-0.214726,NaN,-0.275959,-0.006455,NaN,-0.281024,NaN,-0.296027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-30,-0.017295,0.004176,-0.005137,0.001388,0.000120,0.014811,-0.003187,0.061033,-0.010915,-0.025274,...,-0.003698,-0.047018,0.058622,-0.008779,-0.003766,-0.000159,-0.007455,-0.019563,-0.012925,-0.002122
2020-12-01,-0.021237,-0.006866,-0.009614,-0.014332,0.003022,-0.000125,-0.005934,0.004119,0.023747,-0.002904,...,0.011683,-0.006278,0.005517,-0.004614,-0.004680,-0.024788,-0.029171,0.013661,-0.001732,0.001231
2020-12-02,0.009339,-0.001477,0.009519,-0.011073,-0.004188,-0.007150,0.011752,0.009151,-0.018058,0.033203,...,0.007334,0.014324,0.008985,-0.000935,-0.008407,-0.009441,0.017130,0.040000,-0.012733,0.005400
2020-12-03,0.004619,-0.005733,-0.002476,0.011562,-0.000280,-0.006557,0.004293,-0.018605,0.010091,0.002369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000027
2020-12-04,0.001917,0.007658,0.021520,0.025737,0.012869,0.027439,0.000679,0.015770,0.016738,-0.008004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004438

In [177]:
cumsum_df = daily_return_df.cumsum(axis=0) #vegtelen ablak
cumsum_df

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,-0.420879,-0.395606,NaN,-0.014346,NaN,-0.064721,-0.031990,0.035491,NaN,-0.255485,...,-0.608536,-0.304356,-0.310023,NaN,-0.283451,-0.034815,NaN,-0.322457,NaN,-0.335147
2000-01-04,-0.845685,-0.794628,NaN,-0.051508,NaN,-0.178979,-0.085361,0.002433,NaN,-0.511895,...,-1.196241,-0.663348,-0.600579,NaN,-0.551654,-0.049244,NaN,-0.625717,NaN,-0.675291
2000-01-05,-1.242463,-1.179116,NaN,0.003437,NaN,-0.272192,-0.041298,0.034691,NaN,-0.736701,...,-1.776298,-0.954535,-0.897989,NaN,-0.811100,0.017344,NaN,-0.905065,NaN,-0.997278
2000-01-06,-1.612752,-1.550264,NaN,0.026487,NaN,-0.386615,-0.043322,0.066949,NaN,-0.965684,...,-2.374469,-1.276910,-1.239870,NaN,-1.071814,-0.024625,NaN,-1.174166,NaN,-1.328669
2000-01-07,-2.013804,-1.923909,NaN,0.023014,NaN,-0.476341,0.001014,0.121716,NaN,-1.180417,...,-2.970128,-1.588711,-1.454596,NaN,-1.347773,-0.031081,NaN,-1.455190,NaN,-1.624696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-30,-1248.682814,-1080.776249,-332.289730,2.038375,-793.172041,-372.460539,-0.261854,-3.425645,-146.823503,-1026.509949,...,-1605.371813,-1187.493370,-984.573038,-136.098458,-879.403899,5.498373,-276.789411,-765.892389,-50.667687,-946.226391
2020-12-01,-1248.704052,-1080.783115,-332.299345,2.024042,-793.169019,-372.460664,-0.267788,-3.421526,-146.799756,-1026.512853,...,-1605.360130,-1187.499648,-984.567521,-136.103072,-879.408579,5.473584,-276.818583,-765.878728,-50.669420,-946.225160
2020-12-02,-1248.694713,-1080.784592,-332.289826,2.012969,-793.173207,-372.467814,-0.256036,-3.412375,-146.817814,-1026.479650,...,-1605.352797,-1187.485324,-984.558536,-136.104008,-879.416986,5.464143,-276.801453,-765.838728,-50.682153,-946.219760
2020-12-03,-1248.690094,-1080.790325,-332.292302,2.024531,-793.173487,-372.474370,-0.251743,-3.430980,-146.807722,-1026.477281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-946.219732
2020-12-04,-1248.688177,-1080.782667,-332.270782,2.050268,-793.160618,-372.446931,-0.251064,-3.415210,-146.790985,-1026.485285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-946.215295

### Random Forest ###

In [ ]:
import numpy as np

windows = [5,10,20,40,60]
min_windows = pd.DataFrame().reindex_like(daily_return_df)
concat = None
for w in windows:
    beta_df = daily_return_df.rolling(window=w).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=w).var(), axis=0)
    act_beta_error_df = (daily_return_df - beta_df.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2    
    act_beta_error_df.columns = act_beta_error_df.columns + "_{0}".format(w)
    if concat is not None:
        concat = pd.concat([concat,act_beta_error_df], axis=1)
    else:
        concat = act_beta_error_df
concat

In [378]:
min_windows = pd.DataFrame()
for ticker in daily_return_df.columns:
    prefix = ticker + '_'
    head = [prefix + "5", prefix + "10", prefix + "20", prefix + "40", prefix + "60"]
    min_windows[ticker] = concat[head].idxmin(axis=1).str.replace(prefix,"")
min_windows

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2020,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/20/2020,10,5,40,20,10,5,40,10,5,5,...,10,5,10,5,20,40,5,5,5,5
11/23/2020,20,20,5,20,10,20,40,10,40,5,...,5,10,10,5,5,40,10,5,10,40
11/24/2020,20,20,5,20,10,20,20,10,40,20,...,40,10,10,10,10,5,40,5,10,5
11/25/2020,20,5,10,20,20,10,20,60,10,60,...,5,10,60,60,20,40,10,10,5,5
11/27/2020,5,10,5,60,5,10,20,5,10,10,...,5,20,60,60,5,40,20,20,5,5

In [379]:
Y = min_windows

d = pd.DataFrame(np.zeros((df.shape)), index=df.index, columns=df.columns)

cumsum_df = daily_return_df.cumsum(axis=0) #vegtelen ablak
print(cumsum_df)
# cumsum_df = daily_return_df.rolling(window=100) #rolling min (nem az egeszen, csak pl 100 napon)
# # melyikre teljes\t jobban? fel-1-20... evek vagy a vegtelen
# # follow the leader x ev
# # ftl vegtelen, stb.

# #cumsum.idxmin(axis=1)
# #print(d)
# for ind,row in cumsum_df.idxmin(axis=1).items():
#     #print(ind)
#     #print(row)
#     d.loc[ind,row] = 1

# shifted = d.shift(1) # Mert a tegnapig kapott adatokat nezzuk
# shifted = shifted.mul(df)
# print(df.tail())
# print(df.shift(1).tail())
# shifted.sum(axis=1).cumsum().plot()
# cumsum_df["follow the leader"] = shifted.sum(axis=1).cumsum()
# cumsum_df

# # A mai legjobbat a holnapi legjobbal kell szamolni: shift 1

# # Feature set a kapott beta ablakokkal minden evre, minden modell csak a sajat evet nezi
# # melyik nap 
# # volatilis iszoszakok: beta ablak
# # X: amit felhasznalok feature, Y: a kimenet
# # X-et kitalalom pl. az elmult valamennyi nap alapjan a tulajdonsagok
# # minden napra visszamegyek egy param pl 5 napot, es 
# # daily return, szoras
# # beta window melle a volume


# # kiszamolni minden reszvenyre egy napon belul a legjobb window
# # minden reszveny, datum-ra minden window, es a legkisebbet veszem
# # shift ide nem kell

                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
1/2/2020    0.013057  0.010342  0.005276 -0.021448 -0.003367 -0.021032
1/3/2020    0.021135  0.011974  0.011287 -0.021508  0.002868 -0.010003
1/6/2020    0.029433  0.020383  0.024663  0.053614  0.003636  0.011718
1/7/2020    0.027302  0.021433  0.024213  0.062113  0.007229  0.022607
1/8/2020    0.042077  0.021085  0.028363  0.063851  0.008846  0.020607
...              ...       ...       ...       ...       ...       ...
11/20/2020 -0.229102  0.119007 -0.080462  0.670294  0.258689  0.215344
11/23/2020 -0.226915  0.099622 -0.078108  0.664065  0.264778  0.202343
11/24/2020 -0.215029  0.084070 -0.067610  0.661175  0.275247  0.193124
11/25/2020 -0.213446  0.078092 -0.063950  0.654175  0.272567  0.200763
11/27/2020 -0.218676  0.086998 -0.064808  0.684099  0.272726  0.206426

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
1/2/2020    0.013424  0.047802 -0.006606  0.003005  ... -0.018411 -0.004314
1/3/2020    0.021444  0.059669  0.002190 -0.001520  ... -0.011988 -0.000182
1/6/2020    0.037954  0.067375 -0.003769  0.012657  ... -0.014697 -0.005446
1/7/2020    0.035680  0.045085 -0.016261  0.016653  ... -0.009709 -0.008220
1/8/2020    0.047842  0.044667 -0.027175  0.012681  ... -0.012744 -0.007663
...              ...       ...       ...       ...  ...       ...       ...
11/20/2020  0.212315  0.232695 -0.339508  0.100708  ...  0.247782 -0.436026
11/23/2020  0.203663  0.230240 -0.321535  0.093430  ...  0.228839 -0.417541
11/24/2020  0.206459  0.222657 -0.303184  0.114183  ...  0.221988 -0.400263
11/25/2020  0.214587  0.233734 -0.310097  0.106145  ...  0.220961 -0.395967
11/27/2020  0.214860  0.224642 -0.312160  0.104247  ...  0.210716 -0.400255

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
1/2/2020    0.025214  0.008716  0.012587  0.000425 -0.005201  0.001528
1/3/2020    0.012882  0.025039  0.016826  0.000229  0.004228  0.007169
1/6/2020    0.006750  0.024288  0.020376  0.021566  0.000055  0.006973
1/7/2020    0.019374  0.019157  0.022538  0.017566 -0.004859  0.006382
1/8/2020    0.017563  0.020538  0.039259  0.003080  0.003499  0.013455
...              ...       ...       ...       ...       ...       ...
11/20/2020  0.508396  0.443384  0.050273  0.227411 -0.123044 -0.134808
11/23/2020  0.507347  0.436567  0.044686  0.215398 -0.125296 -0.119147
11/24/2020  0.500636  0.450921  0.058974  0.227978 -0.102065 -0.084033
11/25/2020  0.512278  0.443326  0.056168  0.220099 -0.106786 -0.082321
11/27/2020  0.514173  0.441066  0.057850  0.220046 -0.109843 -0.106554

                 ZTS       SPY
Date
1/2/2020    0.015827  0.004111
1/3/2020    0.028509  0.008003
1/6/2020    0.023650  0.017832
1/7/2020    0.028011  0.016934
1/8/2020    0.024497  0.021610
...              ...       ...
11/20/2020  0.192281  0.032182
11/23/2020  0.181387  0.032686
11/24/2020  0.161131  0.041042
11/25/2020  0.150019  0.039748
11/27/2020  0.149091  0.039281

[230 rows x 506 columns]

AttributeError: 'Rolling' object has no attribute 'idxmin'

In [ ]:
cumsum_df

In [ ]:
# X feature 
# shift-el veszem az elozo x napot, 
pd.DataFrame({"returns" : daily_return_df.stack(), "shifted returns": daily_return_df.shift(1).stack()})
# X feature volume, rolling 
#

In [ ]:
daily_return_df.rolling(10).std()
# szoras, vagy 
daily_return_df.rolling(10).mean()
# Ezekbol csinalom az X-et

# X-bol az Y-t random forest-el szamolom
# A holnapi Y-t a mai X-hez: shift -1 (indexek stimmeljenek)
# Az Y az optimalis window merete

#FTL: minden reszvenyre kell az optimalis window
# --> a kovetkezonek minek kellene lennie

# random forest: default
# szimulacio: megtanitom pl 10-ig(traning), es utana 20-ig(test) ellenorzom
from sicklearn import randomforest
# fit # predict

## step:
# ftl osszehasonlitasa a window-kra, es a vegtelenre
# beta error reszvenyenkent minden ablakra 
## ez lesz az X (+ egy szorast, meg egy arfolyamerteket min, max, volume)
## Y a beta_error reszvenyenkent
# Y minden napra minden reszvenyre kiszamolom az osszes beta window hibajat, es a legkisebb ablakja lesz az Y
# Egy napon belülre számolom az értékeket: 5 érték 

# Fix es X es Y ertekeket megetetetek a random forest-el